// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhz0BiEUiGIZkCuDnxoJLYAKt1sU8LYkY',
    appId: '1:201628190626:web:2c964c71c17a491db4d4fb',
    messagingSenderId: '201628190626',
    projectId: 'loginpractice-33ef1',
    authDomain: 'loginpractice-33ef1.firebaseapp.com',
    storageBucket: 'loginpractice-33ef1.appspot.com',
    measurementId: 'G-JN35RXPGMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktq1CGj8-3Qhu-jsghcbcPUrTV-ZVBSM',
    appId: '1:201628190626:android:7330981858b40776b4d4fb',
    messagingSenderId: '201628190626',
    projectId: 'loginpractice-33ef1',
    storageBucket: 'loginpractice-33ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBH6iQilAXRfrglI4iw76_SiVRr3cEAyU',
    appId: '1:201628190626:ios:654fca103c51d113b4d4fb',
    messagingSenderId: '201628190626',
    projectId: 'loginpractice-33ef1',
    storageBucket: 'loginpractice-33ef1.appspot.com',
    iosBundleId: 'com.example.modernLoginUiAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBH6iQilAXRfrglI4iw76_SiVRr3cEAyU',
    appId: '1:201628190626:ios:b8d9a509ae7c6cefb4d4fb',
    messagingSenderId: '201628190626',
    projectId: 'loginpractice-33ef1',
    storageBucket: 'loginpractice-33ef1.appspot.com',
    iosBundleId: 'com.example.modernLoginUiAuth.RunnerTests',
  );
}
